CREATE TABLE IF NOT EXISTS schedules (
    id UUID PRIMARY KEY,
    route_id UUID REFERENCES routes(id) ON DELETE CASCADE,
    terminal_id UUID REFERENCES terminals(id) ON DELETE CASCADE,
    value DECIMAL(10,2) NOT NULL,
    active boolean NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);