ALTER TABLE seat_configurations
DROP CONSTRAINT IF EXISTS fk_seat_ship;


ALTER TABLE seat_configurations
DROP COLUMN IF EXISTS ship_id,
DROP COLUMN IF EXISTS class,
DROP COLUMN IF EXISTS label,
DROP COLUMN IF EXISTS status,
DROP COLUMN IF EXISTS position,
DROP COLUMN IF EXISTS reserved_until;

ALTER TABLE seat_configurations
ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS left_columns_count INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS right_columns_count INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS prefix boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS nivel INT NOT NULL DEFAULT 0;

