CREATE TABLE IF NOT EXISTS terminals (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    uf CHAR(2) NOT NULL,
    city VARCHAR(255) NOT NULL,
    activity boolean NOT NULL,
    latitude DECIMAL(9,6) NOT NULL,
    longitude DECIMAL(9,6) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);